# Site settings
title: Xavier Yao's Blog
description: > This is Xavier Yao's blog. Here I will share interesting stuff
on computer science and technology and other topics that I came across. But I
may not update my blog regularly. 姚沛然的博客，不定期更新。
url: "http://xavieryao.github.io"
baseurl: ""
logo: "<b>Xavier Yao</b>'s Blog"
paginate: 5
paginate_path: "/page:num/"
owner:
    email: peiran.yao@tuna.tsinghua.edu.cn
    facebook:
        show: true
        name: "Ichihara Rifa"
        url: "https://fb.me/nasya.aidan"
    github:
        show: true
        username: "riefachan"
    twitter:
        show: false
        username: ""
    disqus:
        show: true
        username: "ichihararifa"
sass:
    sass_dir: _sass
    style: compressed
permalink: "/article/:title"
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
highlighter: pygments
gems:
    - jekyll-feed
    - jekyll-paginate
