// Generated by CoffeeScript 1.6.3
(function() {
  var ajax, formatId, markdown, onError, reload;

  markdown = new Markdown.Converter();

  ajax = function(url, tag, onSuccess) {
    var cache, e, request;
    try {
      cache = document.cache[tag];
      if (cache === void 0) {
        request = $.get(url, function(data) {
          cache = markdown.makeHtml(data);
          onSuccess(cache);
          return document.cache[tag] = cache;
        });
        return request.fail(function(jqXHR, textStatus, errThrown) {
          return onError(errThrown.toString());
        });
      } else {
        return onSuccess(cache);
      }
    } catch (_error) {
      e = _error;
      return onError(e.toString());
    }
  };

  onError = function(def) {
    console.error('ERR - The zombile ate your brain!');
    console.error(def);
    return window.location.href = '404.html';
  };

  reload = function(id) {
    var fillContent, page;
    page = document.articles[id];
    if (page === void 0) {
      onError('Page Not Found. ');
      return void 0;
    }
    ajax('articles/' + page.URL, id, fillContent);
    return fillContent = function(data) {
      $('#content').html(data);
      return location.hash = '#' + formatId(id);
    };
  };

  formatId = function(id) {
    var i, result;
    result = id;
    if ((function() {
      var _i, _results;
      _results = [];
      for (i = _i = 0; _i <= 6; i = ++_i) {
        _results.push(result < Math.pow(10, i));
      }
      return _results;
    })()) {
      result = '0' + result;
    }
    return result;
  };

}).call(this);
