// Generated by CoffeeScript 1.6.3
(function() {
  var sectionHeight;

  sectionHeight = function() {
    var $section, margin, total;
    total = $(window).height();
    $section = $('section').css('height', 'auto');
    if ($section.outerHeight(true < total)) {
      margin = $section.outerHeight(true - $section.height());
      return $section.height(total - margin - 20);
    } else {
      return $section.css('height', 'auto');
    }
  };

  $(window).resize(sectionHeight);

  $(document).ready(function() {
    $('#home').hide();
    document.cache.xadf = '2';
    return document.easterEggCount = 0;
  });

}).call(this);
