// Generated by CoffeeScript 1.9.0
(function() {
  var ajax, loadContentTable, markdown, onError, reload, sectionHeight, switchPage,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  markdown = new Markdown.Converter();

  sectionHeight = function() {
    var $section, margin, total;
    total = $(window).height();
    $section = $('section').css('height', 'auto');
    if ($section.outerHeight(true < total)) {
      margin = $section.outerHeight(true - $section.height());
      $section.height(total - margin - 20);
    } else {
      $section.css('height', 'auto');
    }
    return fixScale();
  };

  window.fixScale = function() {
    var addEvent, doc, fix, meta, qsa, scales, type;
    doc = $('section');
    addEvent = 'addEventListener';
    type = 'gesturestart';
    qsa = 'querySelectorAll';
    scales = [1, 1];
    meta = __indexOf.call(doc, qsa) >= 0 ? doc[qsa]('meta[name=viewport]') : [];
    fix = function() {
      meta.content = 'width=device-width,minimum-scale=' + scales[0] + ',maximum-scale=' + scales[1];
      return doc.removeEventListener(type, fix, true);
    };
    if ((meta = meta[meta.length - 1]) && __indexOf.call(doc, addEvent) >= 0) {
      fix();
      scales = [0.25, 1.6];
      return doc[addEvent](type, fix, true);
    }
  };

  $(window).resize(sectionHeight);

  $(document).ready(function() {
    $('#home').hide();
    document.cache = {};
    return $.get('gen/content_table.json', function(result) {
      document.articles = eval(result);
      return switchPage(location.hash);
    });
  });

  switchPage = function(page) {
    var loadIcon;
    $('body').scrollTop(0);
    page = page.replace('#', '');
    loadIcon = '<div class="loadIcon" ><img src="images/octocat-spinner-64.gif" alt="Loading"></img><p>Loading...<br /></p></div>';
    $('content').html(loadIcon);
    if (page === '') {
      page = 'home';
    }
    if (page === 'home') {
      $('#home').fadeOut('slow');
    } else {
      $('#home').fadeIn('slow');
    }
    switch (page) {
      case 'home':
        return ajax('articles/home.md', 'home', function(data) {
          $('#content').html(data);
          fixScale();
          $('body').scrollTop(0);
          return location.hash = '#home';
        });
      case 'index':
        return loadContentTable();
      default:
        return reload(page);
    }
  };

  window.switchPage = switchPage;

  ajax = function(url, tag, onSuccess) {
    var cache, e, request;
    try {
      cache = document.cache[tag];
      if (cache === void 0) {
        request = $.get(url, function(data) {
          cache = markdown.makeHtml(data);
          onSuccess(cache);
          return document.cache[tag] = cache;
        });
        return request.fail(function(jqXHR, textStatus, errThrown) {
          return onError(errThrown.toString());
        });
      } else {
        return onSuccess(cache);
      }
    } catch (_error) {
      e = _error;
      return onError(e.toString());
    }
  };

  onError = function(def) {
    console.error('ERR - The zombile ate your brain!');
    console.error(def);
    return window.location.href = '404.html';
  };

  reload = function(id) {
    var page;
    id = new Number(id);
    page = document.articles[id];
    if (page === void 0) {
      onError('Page Not Found. ');
      return void 0;
    }
    return ajax("articles/" + page.URL, id, function(data) {
      $('#content').html(data);
      $('body').scrollTop(0);
      return location.hash = '#' + id;
    });
  };

  loadContentTable = function() {
    var ct, i, md, _i, _ref;
    if (!document.cache.content_table) {
      ct = document.articles;
      md = "###Table Of Content   \n         \n";
      for (i = _i = _ref = ct.length - 1; _ref <= 0 ? _i < 0 : _i > 0; i = _ref <= 0 ? ++_i : --_i) {
        md = md.concat("<a href=\"javascript:switchPage('" + i + "')\" >" + ct[i].title + "</a>   \n");
      }
      document.cache.content_table = markdown.makeHtml(md);
    }
    $('#content').html(document.cache.content_table);
    $('body').scrollTop(0);
    return location.hash = '#index';
  };

}).call(this);
