// Generated by CoffeeScript 1.7.1
(function() {
  var sectionHeight;

  sectionHeight = function() {
    var $section, margin, total;
    total = $(window).height();
    $section = $('section').css('height', 'auto');
    if ($section.outerHeight(true < total)) {
      margin = $section.outerHeight(true - $section.height());
      return $section.height(total - margin - 20);
    } else {
      return $section.css('height', 'auto');
    }
  };

  $(window).resize(sectionHeight);

  $(document).ready(function() {
    $('#home').hide();
    document.cache = {};
    document.easterEggCount = 0;
    $('#logo').click(function() {
      if (document.easterEggCount === 9) {
        document.easterEggCount = -1;
      }
      document.easterEggCount += 1;
      if (document.easterEggCount === Math.floor(Math.random() * 10)) {
        return switchPage('the_one');
      }
    });
    return $.get('gen/content_table.json', function(result) {
      document.articles = eval(result);
      return switchPage(location.hash);
    });
  });

}).call(this);
